### ISSUE TITLE
42amsterdam master server takes too long to enumerate.

### ISSUE THREAD

**Issue by DreamyCecil** [SamClassicPatch/CoreLib#3]
One of the master servers for the Legacy protocol, 42amsterdam (`master1.42amsterdam.net`), takes way too long to list all of the servers.

Upon selecting it and starting "Search Internet", the game freezes for quite some time (sometimes indefinitely), causing it to appear like it's not responding, before starting to list servers. Refreshing the list or going back and starting the search all over again produces the same result. This makes this master server unusable.

In the Steam patch this doesn't seem to be an issue.

The code for the Legacy protocol has been taken from Serious Engine 1.10 and slightly improved upon. The game running on 1.10 produces the same result if the specified master server is `master1.42amsterdam.net`.

**Comment by tx00100xt** [comment]
1. Добавляем функцию timeout https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTSE/Sources/Engine/GameAgent/GameAgent.cpp#L255
2. Изменяем connect https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTSE/Sources/Engine/GameAgent/GameAgent.cpp#L1039
3. Меняем цикл while (recv) https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTSE/Sources/Engine/GameAgent/GameAgent.cpp#L1261

Я сделал патч - но не компилировал. Думаю в случае ошибок исправить будет легко.
[LegacyClientQuery.patch.txt](https://github.com/SamClassicPatch/CoreLib/files/10807298/LegacyClientQuery.patch.txt)

**Comment by DreamyCecil** [comment]
Применить патч получилось, но код полурабочий. 42amsterdam больше не зависает, но показывает всего два сервера (и другие мастер-серверы тоже) и всё время получает 21 байт. Никаких ошибок, начинающихся с `[LegacyClientQuery]`, не выводит.

Также, я так понимаю, в MSVC 6.0 нет `EINPROGRESS` значения для проверки `errno`. Замена его на число 36 или замена на `WSAEINPROGRESS` с заменами всех `errno` на `WSAGetLastError()` приводят к тому же результату.

**Comment by tx00100xt** [comment]
В nix системах при каждом запросе EINPROGRESS выдаётся. Таблица серверов при этом - клиентом получается. В Windows этого не замечал. При компиляции в VS2015 исходного кода https://github.com/Croteam-official/Serious-Engine с этим исправлением выдаётся полный список серверов.

Ошибка в патче:
>  while(!timeout(_iSocket, 1)) {
>      iErr = recv(_iSocket, _pOnlineAddressBuffer + iLength, iNewLength - iLength, 0);
>      if(iErr <= 0) break;
>      CPutString(".");
>     iLength += iReceived;
>
Должно быть так:
>  while(!timeout(_iSocket, 1)) {
>      iReceived = recv(_iSocket, _pOnlineAddressBuffer + iLength, iNewLength - iLength, 0);
>      if(iReceived <= 0) break;
>      CPutString(".");
>      iLength += iReceived;
>
 iErr из другого кода, забыл поменять. Получаем количество принятых байт в одну переменную, а суммируем с другой)

21 байт - iReceived получает отсюда (еще до цикла while):
>    // Receive response from the master server with the secret key
>   iReceived = recv(_iSocket, strResponse, _ulStringLength, 0);
>
Это как раз длина secure key, к примеру (\basic\\\\secure\LVPXCT)
Поэтому iLength равна количеству байт секретного ключа, а не количеству принятых байт в цикле while

**Comment by DreamyCecil** [comment]
Похоже всё теперь работает, спасибо!
